### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by YayIguess** [MrRean/Splat3D#7]
On Fedora 24, python 3.5.1, python3-qt5-5.6-3,  python3-pyopengl-3.1.1a1-4 
`$ git clone https://github.com/MrRean/Splat3D/`
`$ cd Splat3D`
`$ python3 splat.py`
`Traceback (most recent call last):`
 `File "splat.py", line 1114, in <module>`
 `    main()`
  `File "splat.py", line 1110, in main`
   `    window = MainWindow()`
  `File "splat.py", line 90, in __init__`
   `    if not self.isValidGameFolder(self.gamePath):`
  `File "splat.py", line 135, in isValidGameFolder`
   `    missing = self.checkMissingFolders(folder)`
  `File "splat.py", line 156, in checkMissingFolders`
   `'    Pack/Static/Map', # to load maps`
  `File "splat.py", line 146, in <lambda>`
   `    (lambda path: not os.path.exists(os.path.join(folder, path))),`
  `File "/usr/lib64/python3.5/posixpath.py", line 89, in join`
   `    genericpath._check_arg_types('join', a, *p)`
  `File "/usr/lib64/python3.5/genericpath.py", line 143, in _check_arg_types`
   `    (funcname, s.__class__.__name__)) from None`
`TypeError: join() argument must be str or bytes, not 'NoneType'`

**Comment by MrRean** [comment]
Sounds like Pack/Static/Map hasn't been extracted.

**Comment by YayIguess** [comment]
it should be extracted....  I get [this](http://pastebin.com/sgU7yWLH) from ls -R in the Map directory
